version: '3.5'

services:

  promgrep:
    build: .
    volumes:
      - ./:/app
      - ./dist:/dist
    ports:
      - 8880:8880
  
  prometheus:
    image: flaviostutz/prometheus
    ports:
      - 9090:9090
    environment:
      - SCRAPE_INTERVAL=15s
      - SCRAPE_TIMEOUT=10s
      - DNS_SCRAPE_TARGETS=perfstat@perfstat:8880
      # - STATIC_SCRAPE_TARGETS=mynginx1@nginx1ip:8080 mysqlexporter1@sqlexporter1ip:7070

  grafana:
    image: flaviostutz/grafana:5.2.4
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=mypass

    
